---
# roles/install_elastic/tasks/wait-for-cluster.yml
# UPDATED: Using hostnames instead of IPs

- name: Wait for Elasticsearch nodes to be responsive
  uri:
    url: "{{ 'https' if es_enable_http_ssl else 'http' }}://{{ hostvars[inventory_hostname].node_hostname }}:{{ es_http_base_port + node.port_offset }}/"
    method: GET
    user: "{{ es_api_basic_auth_username if es_enable_http_ssl else omit }}"
    password: "{{ es_api_basic_auth_password if es_enable_http_ssl else omit }}"
    force_basic_auth: "{{ es_enable_http_ssl }}"
    validate_certs: no
    status_code: [200, 401]
    timeout: 30
  register: node_health_checks
  loop: "{{ elasticsearch_nodes }}"
  loop_control:
    loop_var: node
    label: "{{ node.name }}:{{ es_http_base_port + node.port_offset }}"
  until: node_health_checks.status in [200, 401]
  retries: 30
  delay: 10

- name: Get cluster health from first node
  uri:
    url: "{{ 'https' if es_enable_http_ssl else 'http' }}://{{ hostvars[inventory_hostname].node_hostname }}:{{ es_http_base_port }}/_cluster/health?pretty"
    method: GET
    user: "{{ es_api_basic_auth_username if es_enable_http_ssl else omit }}"
    password: "{{ es_api_basic_auth_password if es_enable_http_ssl else omit }}"
    force_basic_auth: "{{ es_enable_http_ssl }}"
    validate_certs: no
    return_content: yes
    timeout: 30
  register: cluster_health
  when: es_api_basic_auth_password is defined

- name: Display cluster health status
  debug:
    msg: |
      🏥 Cluster Health Status
      ======================
      Host: {{ inventory_hostname }} ({{ hostvars[inventory_hostname].node_hostname }})
      Local Nodes: {{ elasticsearch_nodes | length }}
      
      {% if cluster_health is defined and cluster_health.status == 200 %}
      Cluster Status: {{ cluster_health.json.status | upper }}
      Cluster Name: {{ cluster_health.json.cluster_name }}
      Number of Nodes: {{ cluster_health.json.number_of_nodes }}
      Active Shards: {{ cluster_health.json.active_shards }}
      {% else %}
      Cluster Status: Could not retrieve (this is normal during initial setup)
      {% endif %}
      
      🌐 Local Node Access (using hostname):
      {% for node in elasticsearch_nodes %}
      - {{ node.name }}: {{ 'https' if es_enable_http_ssl else 'http' }}://{{ hostvars[inventory_hostname].node_hostname }}:{{ es_http_base_port + node.port_offset }}
      {% endfor %}
      
      ✅ All local nodes are responsive!