- name: create dynamic templates
  uri:
    url: "{{ elastic_address }}/_component_template/ecs@dynamic_templates@all?pretty"
    method: PUT
    body: "{{ lookup('file', 'files/dynamic_templates.json') }}"
    body_format: json
    headers:
      Content-Type: application/json
    user: "{{ elk_user }}"
    password: "{{ elk_password }}"
    validate_certs: no