- name: install and setup Lshell
  block:
    - name: install pip on the server
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Create Lshell cache directory
      file:
        path: "{{ LSHELL_CACHE_DIRECTORY }}"
        state: directory

    - name: Copy lshell files
      unarchive:
        src:  "files/Lshell.tar.gz"
        dest: "{{ LSHELL_CACHE_DIRECTORY }}"

    - name: install Lshell on the server
      command:
        cmd:  pip3 install limited-shell  --break-system-packages --no-index --find-links .
        chdir:  "{{ LSHELL_CACHE_DIRECTORY }}"

    - name: Config Lshell on bda
      template:
        src: templates/Lshell/lshell-bda.conf.j2
        dest: "{{ LSHELL_CONFIG_FILE_PATH }}"
      when: "'BDA' in group_names"

    - name: Config Lshell on other hosts
      template:
        src: templates/Lshell/lshell-all.conf.j2
        dest: "{{ LSHELL_CONFIG_FILE_PATH }}"
      when: "'BDA' not in group_names"

    - name: Cofnig sudoers file
      template:
        src: templates/Lshell/sudoers_lshell.conf.j2
        dest: /etc/sudoers.d/lshell
        owner: root
        group: root
        mode: '0440'
    
    - name: create lshell user
      user:
        name: "{{ LSHELL_USER }}"
        comment: Limited support user
        shell: /usr/local/bin/lshell
        state: present 
        create_home: True 
        password: "{{ Lshell_user_password | password_hash('sha512', 'passlib') }}"