---
- name: Check if /var/www/elastic directory exists
  stat:
    path: /var/www/elastic
  register: directory_stat

- name: Set fact is_new_lb to true if directory does not exist
  set_fact:
    is_new_lb: true
  when: directory_stat.stat.exists == false

- name: Set fact is_new_lb to false if directory exists
  set_fact:
    is_new_lb: false
  when: directory_stat.stat.exists == true
