- name: create fleet server hosts in kibana
  uri:
    url: "{{ kibana_address }}/api/fleet/fleet_server_hosts"
    method: POST
    body: "{{ lookup('template', 'templates/fleet_servers.json.j2') }}"
    body_format: json
    headers:
      Content-Type: application/json
      kbn-xsrf: "true"
    user: "{{ elk_user }}"
    password: "{{ elk_password }}"
    validate_certs: no
    force_basic_auth: yes
  register: fleet_output
  failed_when: fleet_output.status not in [200, 201, 409]
  when: "'SF' in group_names or 'LB' in group_names"
