- name: create Agent Binary Download Sources
  uri:
    url: "{{ kibana_address }}/api/fleet/agent_download_sources"
    method: POST
    user: "{{ elk_user }}"
    password: "{{ elk_password }}"
    body: "{{ lookup('template', 'templates/config_agent_binary.json.j2') }}"
    body_format: json
    headers:
      Content-Type: application/json
      kbn-xsrf: "true"
    validate_certs: no 
    force_basic_auth: yes
  register: agent_output
  failed_when: agent_output.status not in [200, 201, 409]
  when: "'BDA' in group_names"