default_ingest_pipeline_path: "files/ingest_pipelines/default_ingest_piplines"
default_agent_pipeline:
  - all@enrich
  - community_id@enrich
  - dga@enrich
  - dns_question_name_length@enrich
  - geo@enrich
  - naked_ip@enrich
  - network_direction@enrich
  - tld@enrich
  - uri_part@enrich
  - url_length@enrich
  - user_agent@enrich
  - user_agent_length@enrich
  - logs-kibana.audit@custom
