---
logstash_pipeline_content_path: templates/logstash_pipeline_contents
logstash_pipline_list:
  - agentbase_to_kafka: 4
  - agentless_to_kafka: 4
  - apkgate: 2
  - cisco-asa: 3
  - cisco-ftd: 3
  - cisco-ios: 1
  - fortigate: 3
  - fortiweb: 2
  - juniper-srx: 3
  - kaspersky-sc: 1
  - linux: 3
  - metrics: 2
  - nba_to_kafka: 4
  - netflow: 2
  - other: 1
  - padvish: 1
  - sophos: 3
  - suricata: 1
  - vsphere: 2
  - windows: 3
  - zeek: 3
