---
- name: Check and validate LB and SF group conditions
  block:
    - name: Check if LB group has hosts
      set_fact:
        lb_group_has_hosts: "{{ 'LB' in groups and groups['LB'] | length > 0 }}"

    - name: Fail if LB group has hosts but SF group has fewer than 2 hosts
      meta: end_play
      when:
        - (lb_group_has_hosts | default(false))
        - (groups['SF'] | length < 2)
      tags: [cluster, new-node]


- name: Fail if required groups are missing
  meta: end_play
  when: >
    'HOT' not in groups or
    'FROZEN' not in groups or
    'COLD' not in groups or
    'WARM' not in groups or
    'SF' not in groups or
    'BDA' not in groups or
    'NBA' not in groups or
    'SCANNER' not in groups or
    'ELASTICSEARCH' not in groups or
    'LB' not in groups
  tags: [cluster, simple, new-node]
