- name: Install preinstall packages on all hosts
  block:
    - name: Install preinstall packages
      apt:
        name:
          - sudo
          - curl
          - unzip
          - less
          - figlet
          - build-essential
          - openssh-server
          - ca-certificates
          - wget
          - jq
          - debconf-utils
          - telnet
          - systemd-timesyncd
          - net-tools
          - bwm-ng
          - rsyslog
        update_cache: yes
        state: present

    - name: Install nginx on LB, BDA, and SF hosts
      apt:
        name: nginx
        state: present
      when: "'LB' in group_names or 'BDA' in group_names or 'SF' in group_names"

    - name: Delete html directory on LB, BDA, and SF hosts
      file:
        path: /var/www/html
        state: absent
      when: "'LB' in group_names or 'BDA' in group_names or 'SF' in group_names"

    - name: Delete nginx default configuration on BDA hosts
      file:
        path: /etc/nginx/sites-available/default
        state: absent
      when: "'BDA' in group_names"

    - name: Delete symlink to default Nginx configuration in sites-enabled on BDA hosts
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      when: "'BDA' in group_names"
    - name: Remove Nginx package
      apt:
        name: nginx
        state: absent
      when:
        - "'SF' not in group_names"
        - "'BDA' not in group_names"
        - "'LB' not in group_names"

