---
- name: install dependencies
  block:
  - name: Update repository list
    import_tasks: update_repository_list.yml

  - name: Install preinstall packages
    import_tasks: install_preinstall_packages.yml

  - name: Install postinstall packages
    import_tasks: install_postinstall_packages.yml

  - name: Install BDA hosts dependencies
    import_tasks: install_bda_hosts_dependencies.yml

  - name: Install SF hosts dependencies
    import_tasks: install_sf_hosts_dependencies.yml
  
  - name: install scanner node packages
    import_tasks: install_scanner_hosts_dependencies.yml

  - name: install NBA node packages
    import_tasks: install_nba_hosts_dependecies.yml

  - name: change docker default ip address
    import_tasks: change_docker_ip.yml

  - name: Update hosts time zone
    import_tasks: update_time_zone.yml

  tags: [cluster, simple, add-scanner, add-collector]

- name: install dependencies on new-node
  block:
  - name: Update repository list
    import_tasks: update_repository_list.yml

  - name: Install preinstall packages
    import_tasks: install_preinstall_packages.yml

  - name: Install postinstall packages
    import_tasks: install_postinstall_packages.yml

  - name: Install BDA hosts dependencies
    import_tasks: install_bda_hosts_dependencies.yml

  - name: Install SF hosts dependencies
    import_tasks: install_sf_hosts_dependencies.yml

  - name: change docker default ip address
    import_tasks: change_docker_ip.yml

  - name: Update hosts time zone
    import_tasks: update_time_zone.yml

  when: install_needed | default(false) or is_new_lb | default(false)
  tags: [new-node]

- name: Update packages
  import_tasks: update.yml
  tags: update