- name: update time zone of the system
  block:
  - name: "Config system time"
    file:
      src: "/usr/share/zoneinfo/{{ TimeZone }}"
      dest: /etc/localtime
      owner: root
      group: root
      state: link

  - name: "Confirm system time"
    lineinfile:
      path: /etc/timezone
      line: "{{ TimeZone }}"
      create: yes  
      state: present

  - name: "Change the system timezone"
    command: timedatectl set-timezone "{{ TimeZone }}"
    
  when: ansible_date_time.tz != TimeZone  
