---
# Fleet server configuration variables

# Docker Image Configuration
docker_image_name: "registry.apk-group.net/apksiem/beats/elastic-agent"
docker_image_tag: "8.18.2"

# Path Configuration
fleet_base_path: "/usr/share/siem/fleet"
fleet_tmp_path: "/var/siem/tmp/fleet"
fleet_certs_path: "{{ fleet_base_path }}/certs"

# Kibana Configuration (from config_fleet_settings)
elk_user: "siem"
elk_password: "Ch@ng3Th!sP@ssw0rd"
kibana_address: "https://{{ hostvars[groups['BDA'][0]]['ansible_default_ipv4']['address'] }}:5601"

# Artifact Repository Configuration
artifact_repository_url_path: "/downloads/"
artifact_repository_port: "8082"
artifact_repository_ip: "{% if groups['LB'] | length > 0 %}{{ hostvars[groups['LB'][0]]['ansible_default_ipv4']['address'] }}{% else %}{{ hostvars[groups['SF'][0]]['ansible_default_ipv4']['address'] }}{% endif %}"
artifact_repository_url: "http://{{ artifact_repository_ip }}:{{ artifact_repository_port }}{{ artifact_repository_url_path }}"

# Fleet Configuration
fleet_version: "8.18.2"
fleet_default_policy_id: "fleet-server-policy"

# Certificate paths (reference Elasticsearch certs)
certs_base_path: "/usr/share/siem/elasticsearch/certs"
es_conf_dir: "/usr/share/siem/elasticsearch/config"