# roles/install_elastic/tasks/xpack/security/elasticsearch-security-file-multinode.yml
---
- name: Multi-Node File-Based Security Realm Configuration
  block:
    - name: Set fact manage_file_users
      set_fact: 
        manage_file_users: "{{ es_users is defined and es_users.file is defined and es_users.file.keys() | list | length > 0 }}"

    - name: Configure file-based users for each BDA node
      include_tasks: xpack/security/configure-file-security-single-node.yml
      loop: "{{ elasticsearch_nodes | selectattr('group_membership', 'contains', 'BDA') | list }}"
      loop_control:
        loop_var: node
        label: "{{ node.name }}"
      when: manage_file_users

    - name: Display multi-node file-based security summary
      debug:
        msg: |
          🔐 Multi-Node File-Based Security Configuration Complete
          =====================================================
          
          ✅ Configured Nodes:
          {% for node in elasticsearch_nodes | selectattr('group_membership', 'contains', 'BDA') | list %}
          - {{ node.name }}: /usr/share/siem/elasticsearch/{{ node.name }}/config/
          {% endfor %}
          
          👥 Users Configured: {{ es_users.file.keys() | list | length if es_users.file is defined else 0 }}
          🎭 Roles Configured: {{ es_roles.file.keys() | list | length if es_roles.file is defined else 0 }}
          
          📁 Configuration Files (per node):
          - users: User accounts and passwords
          - users_roles: Role assignments  
          - roles.yml: Role definitions
          
          ✅ Ready for native realm configuration!
      when: manage_file_users

  rescue:
    - name: Handle file-based security configuration failure
      debug:
        msg: |
          ❌ File-based security configuration failed!
          
          This may be due to:
          - Container not running
          - Permission issues
          - Invalid user/role definitions
          - elasticsearch-users command issues
          
          Check individual node logs:
          {% for node in elasticsearch_nodes | selectattr('group_membership', 'contains', 'BDA') | list %}
          docker logs {{ node.name }}
          {% endfor %}
          
          Verify container status:
          docker-compose -f /usr/share/siem/elasticsearch/docker-compose.yml ps

  tags: [security, file-realm]