---
es_version: "8.18.2"
es_package_name: "elasticsearch"
es_version_lock: false
es_add_repository: true
es_templates_fileglob: ""
es_repo_base: "http://localhost"
es_apt_key: "{{ es_repo_base }}/GPG-KEY-elasticsearch"
es_apt_url: "deb [trusted=yes] {{ es_repo_base }}/debian stable main"
es_start_service: true
es_restart_on_change: true
es_templates: false
es_user: elasticsearch
es_group: elasticsearch
es_config: {}
es_config_default: "elasticsearch.j2"
# es_config_log4j2: ""
es_config_jvm: "jvm.options.j2"
#Need to provide default directories
es_conf_dir: "/usr/share/siem/elasticsearch/config"
es_pid_dir: "/var/run/elasticsearch"
es_tmp_dir: "/tmp"
es_data_dirs:
  - "/var/lib/elasticsearch"
es_log_dir: "/var/log/elasticsearch"
es_action_auto_create_index: true
es_max_open_files: 65536
es_max_map_count: 262144
es_xpack_license: '{"license":{"uid":"6e57906b-a8d1-4c1f-acb7-73a16edc3934","type":"enterprise","issue_date_in_millis":1523456691721,"expiry_date_in_millis":2838816691721,"max_nodes":null,"max_resource_units":50,"issued_to":"rest-test","issuer":"elasticsearch","signature":"AAAABQAAAA0sKPJdf9T6DItbXVJKAAAAIAo5/x6hrsGh1GqqrJmy4qgmEC7gK0U4zQ6q5ZEMhm4jAAABAKFCHrix7w/xPG14+wdhld1RmphDmXmHfL1xeuI33Ahr1mOUYZ30eR6GZuh7CnK8BQhfq+z63lgctJepWlvwDSgkOvXWLHrJun7YSCrzz1bism0ZHWw7Swb9DO7vePomVBo/Hm9+eX0pV4/cFQNMmbFaX11tqJZYBEO6sNASVAFL7A1ZcVoB2evweGU9pUQYvFvmyzzySf99miDo3NH0XYdownEdtoNgFfmqa3+koCP7onmRZ1h9jhsDOi30RX/DTDXQKW+XoREnOHCoOAJFxwip/c1qaQAOqp1H6+P20ZGr2sIPiU97OVEU9kulm+E+jgiVW3LwGheOXsUOd1B8Mp0=","start_date_in_millis":-1}}'
#These are used for internal operations performed by ansible.
#They do not affect the current configuration
es_api_scheme: "http"
es_api_host: "localhost"
es_api_port: 9200
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_security_api: "_security"
es_license_api: "_license"
es_api_sleep: 15
es_debian_startup_timeout: 10
# JVM custom parameters
es_java_home: ''
es_jvm_custom_parameters: ''
es_heap_dump_path: "/var/lib/elasticsearch"
# SSL/TLS parameters
es_enable_auto_ssl_configuration: true
es_enable_http_ssl: true
es_enable_transport_ssl: true
es_ssl_upload: true
es_ssl_keystore: "files/test2-ca.p12"
es_ssl_keystore_password: "password"
es_ssl_truststore: "files/cert1.p12"
es_ssl_truststore_password: "password"
es_ssl_key: true
es_ssl_key_password: ""
es_ssl_certificate: true
es_ssl_certificate_authority: true
es_ssl_certificate_path: "{{ es_conf_dir }}/certs"
es_ssl_verification_mode: "certificate"
es_validate_certs: "no"
es_delete_unmanaged_file: true
es_delete_unmanaged_native: true
es_api_basic_auth_username: elastic
es_api_basic_auth_password: Ch@ng3Th!sP@ssw0rd
