---
reserved_xpack_users: ["elastic", "kibana", "logstash_system"]
sysd_config_file: "/etc/systemd/system/elasticsearch.service.d/override.conf"

# Docker-specific variables
# Docker Configuration (MUST MATCH ACTUAL PATHS)
elasticsearch_docker_image: "docker.apk-group.net/elasticsearch"
elasticsearch_docker_path: "/usr/share/siem/elasticsearch"
elasticsearch_data_path: "{{ elasticsearch_docker_path }}/data"
elasticsearch_logs_path: "{{ elasticsearch_docker_path }}/logs"
elasticsearch_config_path: "{{ elasticsearch_docker_path }}/config" 
elasticsearch_certs_path: "{{ elasticsearch_docker_path }}/certs"
elasticsearch_compose_path: "{{ elasticsearch_docker_path }}/docker-compose.yml"

# SSL Certificate Configuration (CRITICAL - MUST BE CORRECT)
es_ssl_certificate_path: "{{ elasticsearch_certs_path }}"
es_enable_http_ssl: true
es_enable_transport_ssl: true
es_enable_security: true
es_ssl_verification_mode: "certificate"

# Cluster Configuration
es_cluster_name: "siem-cluster"
es_heap_size: "1g"

# Make sure these are also set correctly:
es_validate_certs: no
es_api_basic_auth_username: "elastic"
# es_api_basic_auth_password should be in your inventory or group_vars

es_config:
  cluster.name: "siem-cluster"
es_users:
  file:
    logstash_user:
      password: rgaerasdcvgbaerwefawedawdscvfgt
      roles:
        - kibana4_server
    elastic_maps:
      password: "P@ssw0rdM@t@6810"
      roles:
        - monitoring_user
        - apm_system
    siem:
      password: Ch@ng3Th!sP@ssw0rd
      roles:
        - superuser
        - monitoring_user
        - kibana_admin
        - admin
        - kibana_system
    es_admin:
      password: Ch@ng3Th!sP@ssw0rd
      roles:
        - admin
        - superuser
        - monitoring_user
        - kibana_admin
    testUser:
      password: Ch@ng3Th!sP@ssw0rd
      roles:
        - power_user
        - user
es_roles:
  file:
    kibana4_server:
      cluster:
        - monitor
      indices:
        - names: ".kibana"
          privileges:
            - all
    admin:
      cluster:
        - all
      indices:
        - names: "*"
          privileges:
            - all
    ems:
      cluster:
        - monitor
    power_user:
      cluster:
        - monitor
      indices:
        - names: "*"
          privileges:
            - all
    user:
      indices:
        - names: "*"
          privileges:
            - read

# Used in update process
updater_user_username: "updater_user"