---
# Version and Docker Configuration
es_version: "8.18.2"
elasticsearch_docker_image: "docker.apk-group.net/elasticsearch"

# ADDED: Base paths that were missing
elasticsearch_base_path: "/usr/share/siem/elasticsearch"
certs_base_path: "/usr/share/siem/elasticsearch/certs"
kibana_base_path: "/usr/share/siem/kibana"

# Docker Configuration (CRITICAL - MUST MATCH ACTUAL PATHS)
elasticsearch_docker_path: "{{ elasticsearch_base_path }}"
elasticsearch_data_path: "{{ elasticsearch_base_path }}/data"
elasticsearch_logs_path: "{{ elasticsearch_base_path }}/logs"
elasticsearch_config_path: "{{ elasticsearch_base_path }}/config" 
elasticsearch_certs_path: "{{ certs_base_path }}"
elasticsearch_compose_path: "{{ elasticsearch_base_path }}/docker-compose.yml"


# Network Configuration
es_http_base_port: 9200
es_transport_base_port: 9300

# SSL Certificate Configuration (CRITICAL - MUST BE CORRECT)
es_ssl_certificate_path: "{{ certs_base_path }}"
es_enable_http_ssl: true
es_enable_transport_ssl: true
es_enable_security: true
es_ssl_verification_mode: "certificate"
es_validate_certs: false

# Cluster Configuration
es_cluster_name: "siem-cluster"
es_heap_size: "1g"

# Authentication Configuration
es_api_basic_auth_username: "elastic"
es_api_basic_auth_password: "YourVerySecureElasticsearchPassword123!"

# Basic Elasticsearch Configuration
es_config:
  cluster.name: "{{ es_cluster_name }}"
  action.auto_create_index: true
  cluster.max_shards_per_node: 2000

# File-based Users Configuration
es_users:
  file:
    logstash_user:
      password: "rgaerasdcvgbaerwefawedawdscvfgt"
      roles:
        - kibana4_server
    elastic_maps:
      password: "P@ssw0rdM@t@6810"
      roles:
        - monitoring_user
        - apm_system
    siem:
      password: "Ch@ng3Th!sP@ssw0rd"
      roles:
        - superuser
        - monitoring_user
        - kibana_admin
        - admin
        - kibana_system
    es_admin:
      password: "Ch@ng3Th!sP@ssw0rd"
      roles:
        - admin
        - superuser
        - monitoring_user
        - kibana_admin
    testUser:
      password: "Ch@ng3Th!sP@ssw0rd"
      roles:
        - power_user
        - user

# File-based Roles Configuration
es_roles:
  file:
    kibana4_server:
      cluster:
        - monitor
      indices:
        - names: ".kibana"
          privileges:
            - all
    admin:
      cluster:
        - all
      indices:
        - names: "*"
          privileges:
            - all
    ems:
      cluster:
        - monitor
    power_user:
      cluster:
        - monitor
      indices:
        - names: "*"
          privileges:
            - all
    user:
      indices:
        - names: "*"
          privileges:
            - read

# Legacy variables for compatibility
reserved_xpack_users: ["elastic", "kibana", "logstash_system"]
sysd_config_file: "/etc/systemd/system/elasticsearch.service.d/override.conf"

# Used in update process
updater_user_username: "updater_user"

# JVM Configuration
es_jvm_custom_parameters: []

# Additional configuration defaults
es_enable_auto_ssl_configuration: true
es_ssl_upload: true
es_ssl_key: true
es_ssl_certificate: true
es_ssl_certificate_authority: true
es_delete_unmanaged_file: true
es_delete_unmanaged_native: true

# Performance and system settings
es_max_open_files: 65536
es_max_map_count: 262144

# API settings
es_api_scheme: "https"
es_api_host: "localhost"
es_api_port: 9200
es_api_uri: "{{ es_api_scheme }}://{{ es_api_host }}:{{ es_api_port }}"
es_security_api: "_security"
es_license_api: "_license"
es_api_sleep: 15

# X-pack License
es_xpack_license: '{"license":{"uid":"6e57906b-a8d1-4c1f-acb7-73a16edc3934","type":"enterprise","issue_date_in_millis":1523456691721,"expiry_date_in_millis":2838816691721,"max_nodes":null,"max_resource_units":50,"issued_to":"rest-test","issuer":"elasticsearch","signature":"AAAABQAAAA0sKPJdf9T6DItbXVJKAAAAIAo5/x6hrsGh1GqqrJmy4qgmEC7gK0U4zQ6q5ZEMhm4jAAABAKFCHrix7w/xPG14+wdhld1RmphDmXmHfL1xeuI33Ahr1mOUYZ30eR6GZuh7CnK8BQhfq+z63lgctJepWlvwDSgkOvXWLHrJun7YSCrzz1bism0ZHWw7Swb9DO7vePomVBo/Hm9+eX0pV4/cFQNMmbFaX11tqJZYBEO6sNASVAFL7A1ZcVoB2evweGU9pUQYvFvmyzzySf99miDo3NH0XYdownEdtoNgFfmqa3+koCP7onmRZ1h9jhsDOi30RX/DTDXQKW+XoREnOHCoOAJFxwip/c1qaQAOqp1H6+P20ZGr2sIPiU97OVEU9kulm+E+jgiVW3LwGheOXsUOd1B8Mp0=","start_date_in_millis":-1}}'