- name: Check sources.list file exist
  file:
    path: "{{ apt_sources_list_file_path }}"
    state: touch
    mode: '0644'
  tags: [cluster, simple]

- name: Setup hosts Apt sources.list
  lineinfile:
    dest: "{{ apt_sources_list_file_path }}"
    regexp: "deb [trusted=yes] http://{{ main_repository_ip_address }} siem main"
    line: "deb [trusted=yes] http://{{ main_repository_ip_address }} siem main"
  tags: [cluster, simple]

- name: Update Apt source list
  apt:
    update_cache: yes
  tags: [cluster, simple, update]
