---

- name: install and config kafka
  block:
    - name: Copy kaf binary to /usr/bin/kaf
      copy:
        src: files/kaf
        dest: /usr/bin/kaf
        mode: 0755

    - name: Copy kafka-topics binary to /usr/bin/kafka-topics
      copy:
        src: files/kafka-topics
        dest: /usr/bin/kafka-topics
        mode: 0755

    - name: Copy kaf config to /root/kaf-config
      copy:
        src: files/kaf-config
        dest: /root/kaf-config
        mode: 0755
      
  when: "'SF' in group_names or 'COLLECTOR' in group_names"
  tags:
        - cluster
        - simple  
        - add-collector