- name: Add new host to xpack.fleet.outputs.hosts in kibana.yml
  block:
    - name: Check if host already exists in kibana.yml
      shell: grep -q "https://{{ ansible_default_ipv4.address }}:9200" /etc/kibana/kibana.yml
      register: host_exists
      failed_when: false
      changed_when: false
    

    - name: Add new host to xpack.fleet.outputs.hosts
      shell: |
        sed -i '/xpack.fleet.outputs:/,/ca_trusted_fingerprint:/ {
          /hosts:/,/ca_trusted_fingerprint:/ {
            /ca_trusted_fingerprint:/i\      - "https://{{ ansible_default_ipv4.address }}:9200"
          }
        }' /etc/kibana/kibana.yml
      when: host_exists.rc != 0

    - name: Verify the change
      shell: grep -A 10 "xpack.fleet.outputs:" /etc/kibana/kibana.yml
      register: verify_output
      changed_when: false


  when: "'HOT' in group_names and install_needed | default(false)"
  notify:
    - Restart Kibana
  tags: new-node  
  delegate_to: localhost