- name: "This task just need to run on BDA hosts"
  block:
    - name: create Geo ip database folder
      file:
        path: "/var/www/geoipDB_ES"
        state: directory
    - name: "Copy geo IP database to destination"
      unarchive:
        src: "files/Offline_Geoip_db.zip"
        dest: "/var/www/geoipDB_ES"
    - name: "Copy nginx config file to serve geo ips"
      copy:
        src: "files/geoip.conf"
        dest: "/etc/nginx/conf.d/"
    - name: "Disable nginx default web page"
      command: 'echo "" > /etc/nginx/sites-available/default'
    - name: Enable nginx module
      service:
        name: nginx
        state: started
        enabled: true
    - name: Load nginx configuration file
      command: nginx -s reload
  when: "'BDA' in group_names"