---
# Create Kibana directory structure
- name: Create base Kibana directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"
  loop:
    - "{{ kibana_docker_path }}"
    - "{{ kibana_data_path }}"
    - "{{ kibana_logs_path }}"
    - "{{ kibana_config_path }}"
    - "{{ kibana_certs_path }}"

- name: Display directory creation status
  debug:
    msg: |
      ✅ Kibana directories created:
      - Base: {{ kibana_docker_path }}
      - Data: {{ kibana_data_path }}
      - Logs: {{ kibana_logs_path }}
      - Config: {{ kibana_config_path }}
      - Certs: {{ kibana_certs_path }}