- name: Install Kibana Docker just on BDA hosts
  block:
    - name: Create Kibana Docker directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "1000"
        group: "1000"
        mode: "0755"
      with_items:
        - "{{ kibana_docker_path }}"
        - "{{ kibana_data_path }}"
        - "{{ kibana_logs_path }}"
        - "{{ kibana_config_path }}"
        - "{{ kibana_certs_path }}"

    - name: Copy Kibana Docker image
      synchronize:
        src: files/kibana-{{ kibana_version }}-docker.tar.gz
        dest: /var/cache/siem/kibana-{{ kibana_version }}-docker.tar.gz

    - name: Load Kibana Docker image
      command: docker load -i /var/cache/siem/kibana-{{ kibana_version }}-docker.tar.gz

    - name: Remove temporary Docker image file
      file:
        path: /var/cache/siem/kibana-{{ kibana_version }}-docker.tar.gz
        state: absent
  when: "'BDA' in group_names"