---

- name: Download elastic agent in simple mode
  tags: simple
  import_tasks: elastic-agent-simple.yml    



- name : Download elastic agent in cluster mode
  tags: cluster
  import_tasks: elastic-agent-cluster.yml
  when: 
    - "'LB' in group_names"
    - "groups['LB'] | length > 0"  


- name: Download elastic agent in cluster mode
  tags: cluster
  import_tasks: elastic-agent-simple.yml
  when: "('LB' not in groups or groups['LB'] | length == 0) and inventory_hostname in groups['SF']"

- name : Download elastic agent in new node
  tags: new-node 
  import_tasks: elastic-agent-cluster.yml
  when:
    - "'LB' in group_names"
    - "groups['LB'] | length > 0"
    - is_new_lb | default(false)