galaxy_info:
  author: APK Platform
  description: Deploy and configure logstash
  company: Amn Pardazan Kavir

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: "2.1"

  galaxy_tags: []

dependencies: []
