---
- name: Install Ipsec
  block:
    - name: Install siem-ipsec-manager and strongswan
      apt:
        name: 
          - siem-ipsec-manager
          - strongswan
        state: present

    - name: Create Kibana plugins cache directory
      file:
        path: /var/cache/siem/kibana_plugins
        state: directory

    - name: Find all Kibana plugins (.zip files) in the files directory
      find:
        paths: "{{ role_path }}/files/"
        patterns: "*.zip"
      register: kibana_plugins_zip_files

    - name: Copy Kibana plugins (ZIP files)
      synchronize:
        src: "{{ item.path }}"
        dest: /var/cache/siem/kibana_plugins/
        compress: yes
        delete: yes
        recursive: yes
      loop: "{{ kibana_plugins_zip_files.files }}"
      when: kibana_plugins_zip_files.matched > 0

    - name: Install Kibana plugins
      command: >
        /usr/share/kibana/bin/kibana-plugin install file:///var/cache/siem/kibana_plugins/{{ item | basename }}
      loop: "{{ kibana_plugins_zip_files.files | map(attribute='path') | list }}"
      args:
        chdir: /usr/share/kibana/bin
      when: kibana_plugins_zip_files.matched > 0
      register: plugin_installation
      ignore_errors: true

    - name: Display installation results
      debug:
        var: plugin_installation.results