- name: Check for update possibly
  block:
  - name: check current elasticsearch version
    command:
      cmd:  /usr/share/elasticsearch/bin/elasticsearch --version 
    register: elasticsearch_version_cmd
  
  - name: set fact for installed elasticsearch version
    set_fact:
      installed_elasticsearch_version={{ elasticsearch_version_cmd.stdout.split(',')[0].split(':')[1].strip(' ') }}

  - name: set fact for installed elasticsearch major version
    set_fact:
      installed_elasticsearch_major_version={{ installed_elasticsearch_version.split('.')[0] }}

  - name: set fact for installer elasticsearch major version
    set_fact:
      installer_elasticsearch_major_version={{ es_version.split('.')[0] }}

  - name: Fail if installed major version is not same as installer major version
    meta: end_play
    when: "installer_elasticsearch_major_version != installed_elasticsearch_major_version"

  - name: Fail if installer version is same with installed elasticsearch
    meta: end_play
    when: "installed_elasticsearch_version == installer_elasticsearch_major_version"

