---
- name: Reenable shard allocation
  uri:
    url: https://{{ ansible_default_ipv4.address }}:9200/_cluster/settings?pretty
    user: "{{ updater_user_username }}"
    method: PUT
    password: "{{ updater_user_password }}"
    force_basic_auth: yes
    validate_certs: "{{ es_validate_certs }}"
    body:
      persistent:
        cluster.routing.allocation.enable: null
    body_format: json
    headers:
      Content-Type: application/json
  when: "'BDA' in group_names"