---
- name: "Run this module just on BDA"
  block:
    - name: Create siem cache directory
      file:
        path: /var/cache/siem
        state: directory
        
    - name: Create map directory
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/usr/share/siem/map"
        - "/usr/share/siem/map/certs"

    - name: Copy elastic-maps-server config file
      template:
        src: elastic-maps-server.yml.j2
        dest: /usr/share/siem/map/elastic-maps-server.yml

    - name: copy ca-certs
      copy:
        src: /var/lib/kibana/certs/ca/ca.crt
        dest: /usr/share/siem/map/certs/ca.crt
        remote_src: yes

    - name: copy kibana certificate private key file
      copy:
        src: /var/lib/kibana/certs/kibana/kibana.key
        remote_src: yes
        dest: /usr/share/siem/map/certs/kibana.key

    - name: copy kibana certificate file
      copy:
        src: /var/lib/kibana/certs/kibana/kibana.crt
        remote_src: yes
        dest: /usr/share/siem/map/certs/kibana.crt

    - name: chown certs
      command: chown -R 1000:1000 /usr/share/siem/map/certs
