---

- name: Restart Elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
  when: install_needed | default(false)


- name: Restart Kibana
  service:
    name: kibana
    state: restarted
  delegate_to: localhost