---
- name: Update zeek network interface
  block:
    - name: Update Zeek interface in node.cfg
      ansible.builtin.replace:
        path: "{{ zeek_configuration_directory }}/node.cfg"
        regexp: '^(interface=).*'
        replace: '\1{{ nba_interface_name }}'

    - name: load changes inside the zeek
      command: "{{ zeek_binaries_folder }}/zeekctl deploy"
  when: interface_check.rc == 0

- name: Config zeek service
  block:
    - name: copy zeek systemd file
      copy:
        src: files/zeek.service
        dest: /etc/systemd/system
  notify:
    - Reload Zeek
    - Restart Zeek
