- name: Ensure SIEM file directory exists
  file: 
    path: "{{ siem_file_directory }}"
    state: directory

- name : Create Zeek plugins directory
  file:
    path: "{{ zeek_plugins_directory }}"
    state: directory


- name: Copy Zeek plugins bundle to the NBA server
  copy:
    src: "files/{{ zeek_plugins_file_name }}"
    dest:  "{{ zeek_plugins_directory }}"

- name: Import plugins into Zeek
  command: "{{ zeek_binaries_folder }}/zkg unbundle --force --replace {{ zeek_plugins_file_name }}"
  args:
    chdir: "{{ zeek_plugins_directory }}"

- name: Load the Zeek plugins
  lineinfile:
    path: "{{ zeek_logrotate_config_dir }}/local.zeek"
    line: "@load ./{{ item }}"
  loop:
    - "hassh"
    - "zeek-long-connections"
    - "ja4"
    - "smtp-url-analysis"
    - "bzar"
    - "ja3"