- name: Enable JSON logging format on Zeek
  block:
    - name: copy logs.zeek file
      copy:
        src: "files/logs.zeek"
        dest: "{{ zeek_configuration_directory }}"

    - name: load the configuration file inside the zeek config
      lineinfile:
        path: "{{ zeek_logrotate_config_dir }}/local.zeek"
        line: "@load {{ zeek_configuration_directory }}/logs.zeek"



- name: change the log directory
  block:
    - name: create the log directory
      file:
        path: /var/log/zeek
        state: directory

    - name: change the zeek log output directory
      command: sed -i 's|/opt/zeek/logs|/var/log/zeek|g' {{ zeek_configuration_directory }}/zeekctl.cfg
