---
- name : Configure Nginx webserver to serve artifact files in cluster mode
  tags: [cluster, update]
  import_tasks: configure_nginx_to_server_artifacts_files_cluster.yml
  when: 
    - "'LB' in group_names"
    - "groups['LB'] | length > 0"
  
- name: Configure Nginx webserver to serve artifact files in cluster mode
  tags: [cluster, update]
  import_tasks: configure_nginx_to_server_artifacts_files_simple.yml
  when: "('LB' not in groups or groups['LB'] | length == 0) and inventory_hostname in groups['SF']"

- name: "Configure Nginx webserver to serve artifact files in simple mode"
  tags: [simple, update]
  import_tasks: configure_nginx_to_server_artifacts_files_simple.yml

- name: Configure Nginx webserver to serve artifact files in new node
  tags: [new-node]
  import_tasks: configure_nginx_to_server_artifacts_files_cluster.yml
  when:
    - "'LB' in group_names"
    - "groups['LB'] | length > 0"
    - is_new_lb | default(false)

- name: "Remove Elasticsearch artifacts on SF hosts"
  import_tasks: remove_artifacts_on_sf.yml
  when:
    - "'SF' in group_names"
    - "groups['LB'] | length > 0"
  tags: new-node

- name: "Configure Nginx webserver to serve artifact files in collector node"
  import_tasks: configure_nginx_to_server_artifacts_files_simple.yml
  when: "'COLLECTOR' in group_names"
  tags: add-collector