---
# roles/install_elastic/handlers/main.yml

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: restart elasticsearch container
  docker_compose:
    project_src: "{{ elasticsearch_docker_path }}"
    restarted: yes
    services:
      - elasticsearch

- name: stop elasticsearch container
  docker_compose:
    project_src: "{{ elasticsearch_docker_path }}"
    state: absent
    services:
      - elasticsearch

- name: start elasticsearch container
  docker_compose:
    project_src: "{{ elasticsearch_docker_path }}"
    state: present
    services:
      - elasticsearch

- name: reload elasticsearch container
  shell: |
    docker exec elasticsearch-{{ inventory_hostname }} \
    kill -HUP $(docker exec elasticsearch-{{ inventory_hostname }} pgrep -f elasticsearch)
  ignore_errors: yes

# Legacy handlers for compatibility
- name: Start Nginx
  service:
    name: nginx
    state: started
    enabled: yes
    
- name: Reload Nginx
  command: "nginx -s reload"

- name: Test Nginx
  command: "nginx -t"

- name: reload systemd configuration
  systemd:
    daemon_reload: true

- name: restart elasticsearch
  debug:
    msg: "Legacy handler - using Docker restart instead"
  changed_when: false
  notify: restart elasticsearch container