---
- name: copy Suricata configuration example file for helper
  copy:
    src: "files/suricata.yaml"
    dest: "{{ suricata_config_file }}.example"

- name: Update pfring interface in Suricata configuration using template
  template:
    src: "templates/suricata.yaml.j2"
    dest: "{{ suricata_config_file }}"
  notify: Restart Suricata
  when: interface_check.rc == 0

- name: update suricata rules
  block:
    - name: delete the suricata default rules directory
      file:
        path: "{{ suricata_rules_directory }}"
        state: absent

    - name: Recreate the rules directory
      file:
        path: "{{ suricata_rules_directory }}"
        state: directory

    - name: extract and import the suricata rules
      unarchive:
        src: "files/{{ suricata_rules_filename }}"
        dest: "{{ suricata_rules_directory }}"
  notify: Restart Suricata