---
- name: "Install logstash tool"
  tags: [cluster , simple, add-collector, new-node]
  import_tasks: install_logstash_tool.yml

- name: "Configure logstash tool"
  tags: [cluster , simple]
  import_tasks: configure_logstash.yml

- name: "Start logstash service"
  tags: [cluster , simple]
  import_tasks: start_logstash_service.yml

- name: install logstash in new Sf node
  block:
    - name: "Configure logstash tool"
      import_tasks: configure_logstash.yml

    - name: "Start logstash service"
      import_tasks: start_logstash_service.yml
  tags: new-node
  when: install_needed | default(false) and is_elasticsearch

- name: Update logstash
  import_tasks: update.yml
  tags: update
