- name: "this block must be run on SF servers"
  block:
    - name: "Start Logstash Docker containers"
      command: docker compose -f {{ logstash_compose_path }} up -d

    - name: Wait for Logstash to be ready
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:9600/_node/stats"
        method: GET
        status_code: 200
      register: logstash_health
      until: logstash_health.status == 200
      retries: 30
      delay: 10
  when: "'SF' in group_names"
