- name: import and config endpoints agent polices
  block:
    - name: create endpoints package polices
      uri:
        url: "{{ kibana_address }}/api/fleet/package_policies"
        method: POST
        body: "{{ lookup('file', '{{ item }}') }}"
        body_format: json
        headers:
          Content-Type: application/json
          kbn-xsrf: "true"
        user: "{{ elk_user }}"
        password: "{{ elk_password }}"
        validate_certs: no
        force_basic_auth: yes
        timeout: 200
      register: config_endpoints_polices_output
      failed_when: config_endpoints_polices_output.status not in [200, 201, 409]
      with_fileglob:
        - "files/package_polices_defaults/endpoints/*.json"

    - name: Config endpoints package polices
      uri:
        url: "{{ kibana_address }}/api/fleet/package_policies/{{ item }}"
        method: PUT
        body: "{{ lookup('file', 'files/endpoint_configurations/{{ item }}') }}"
        body_format: json
        headers:
          Content-Type: application/json
          kbn-xsrf: "true"
        user: "{{ elk_user }}"
        password: "{{ elk_password }}"
        validate_certs: no
        force_basic_auth: yes
        timeout: 200
      register: config_endpoints_package_polices_output
      failed_when: config_endpoints_package_polices_output.status not in [200, 201, 409]
      with_items:
        - "endpoint-coordinator-nodes-policy"
        - "endpoint-linux-db-default"
        - "endpoint-linux-servers-default"
        - "endpoint-siem-nodes-policy"
        - "endpoint-windows-dc-dns-default"
        - "endpoint-windows-exchange-default"
        - "endpoint-windows-servers-default"
        - "endpoint-linux-client-default"
        - "endpoint-linux-forensic-policy"
        - "endpoint-linux-web-default"
        - "endpoint-windows-client-default"
        - "endpoint-windows-dhcp-default"
        - "endpoint-windows-forensic-policy"
        - "endpoint-windows-web-db-default"
        