---
- name: config and import package polices
  block:
    - name: import and config windoes related package polices
      uri:
        url: "{{ kibana_address }}/api/fleet/package_policies"
        method: POST
        body: "{{ lookup('file', '{{ item }}') }}"
        body_format: json
        headers:
          Content-Type: application/json
          kbn-xsrf: "true"
        user: "{{ elk_user }}"
        password: "{{ elk_password }}"
        validate_certs: no
        force_basic_auth: yes
        timeout: 200
      register: import_polices_output
      failed_when: import_polices_output.status not in [200, 201, 409]
      with_fileglob:
        - "files/package_polices_defaults/windows/*.json"

    - name: import and config network related package polices
      uri:
        url: "{{ kibana_address }}/api/fleet/package_policies"
        method: POST
        body: "{{ lookup('file', '{{ item }}') }}"
        body_format: json
        headers:
          Content-Type: application/json
          kbn-xsrf: "true"
        user: "{{ elk_user }}"
        password: "{{ elk_password }}"
        validate_certs: no
        force_basic_auth: yes
        timeout: 200
      register: import_polices_output
      failed_when: import_polices_output.status not in [200, 201, 409]
      with_fileglob:
        - "files/package_polices_defaults/network/*.json"

    - name: import and config linux related package polices
      uri:
        url: "{{ kibana_address }}/api/fleet/package_policies"
        method: POST
        body: "{{ lookup('file', '{{ item }}') }}"
        body_format: json
        headers:
          Content-Type: application/json
          kbn-xsrf: "true"
        user: "{{ elk_user }}"
        password: "{{ elk_password }}"
        validate_certs: no
        force_basic_auth: yes
        timeout: 200
      register: import_polices_output
      failed_when: import_polices_output.status not in [200, 201, 409]
      with_fileglob:
        - "files/package_polices_defaults/linux/*.json"

    - name: import and config integrations related package polices
      uri:
        url: "{{ kibana_address }}/api/fleet/package_policies"
        method: POST
        body: "{{ lookup('file', '{{ item }}') }}"
        body_format: json
        headers:
          Content-Type: application/json
          kbn-xsrf: "true"
        user: "{{ elk_user }}"
        password: "{{ elk_password }}"
        validate_certs: no
        force_basic_auth: yes
        timeout: 200
      register: import_polices_output
      failed_when: import_polices_output.status not in [200, 201, 409]
      with_fileglob:
        - "files/package_polices_defaults/integrations/*.json"

    - name: import and config others package polices
      uri:
        url: "{{ kibana_address }}/api/fleet/package_policies"
        method: POST
        body: "{{ lookup('file', '{{ item }}') }}"
        body_format: json
        headers:
          Content-Type: application/json
          kbn-xsrf: "true"
        user: "{{ elk_user }}"
        password: "{{ elk_password }}"
        validate_certs: no
        force_basic_auth: yes
        timeout: 200
      register: import_polices_output
      failed_when: import_polices_output.status not in [200, 201, 409]
      with_fileglob:
        - "files/package_polices_defaults/others/*.json"