- name: Config default agent polices
  uri:
    url: "{{ kibana_address }}/api/fleet/agent_policies"
    method: POST
    body: "{{ lookup('file', '{{ item }}') }}"
    body_format: json
    headers:
      Content-Type: application/json
      kbn-xsrf: "true"
    user: "{{ elk_user }}"
    password: "{{ elk_password }}"
    validate_certs: no
    force_basic_auth: yes
    timeout: 200
  register: config_polices_output
  failed_when: config_polices_output.status not in [200, 201, 409]
  with_fileglob:
    - "files/default_agent_policeis/*.json"

