- name: generate and config motd banner
  import_tasks: motd_banner.yml
  tags: [simple, cluster, update]

- name: generate and config motd banner for collector hosts
  import_tasks: motd_banner.yml
  when: "'COLLECTOR' in group_names"
  tags: [simple, add-collector]

- name: generate setupinfo file
  import_tasks: generate_setupinfo.yml
  when: "'BDA' in group_names and TimeZone is defined"
  tags: [simple, cluster]

- name: reboot hosts
  import_tasks: reboot_hosts.yml
  tags: [simple, cluster]